spring:
  datasource:
    url: jdbc:mysql://localhost:3306/publicPlus
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
file:
  dir: C:\Users\HWS\Documents\WEB1_2_PublicPlus_BE\upload\