name: CICD TO ECS

on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-2
  ECR_URL: 533267244952.dkr.ecr.ap-northeast-2.amazonaws.com/publicplus
jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
          
      - name: Gradle 명령 실행 권한 부여
        run: ls -al && chmod +x ./gradlew
        shell: bash

      - name: Gradle로 프로젝트 Build
        run: ./gradlew build -x test
      
